name: test

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: run
        run: bash ./run.sh
      - name: commit
        run: |
          git config --global user.email 2295823382@qq.com
          git config --global user.name qian-bi
          git add .
          git commit -m "update" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
